# Generated by Django 4.2 on 2024-02-20 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('sentimental_value', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('monetary_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ownership_status', models.CharField(choices=[('Sole Owner', 'Sole Owner'), ('Joint Owner', 'Joint Owner'), ('Other', 'Other')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('desired_disposition', models.CharField(choices=[('Keep', 'Keep'), ('Sell', 'Sell'), ('Donate', 'Donate'), ('Other', 'Other')], max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item_images/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='item.item')),
            ],
        ),
    ]
